#! /usr/bin/env bash

#  echo -e "a\nb\n" |  take 2
#  > b
function take { 
    awk "NR == $1 { print; exit 0; }"; 
}

function join {
    tr -d "\n"
}

function ju {
    first=$1
    shift;
    cd $(find $first -type d | fzf --query="$@")
}

function get_ps1 {
    tput -S <<< "
        cup 0 0
        el
        cup 1 0
        el
        cup 0 0
    "
    host=$(hostname)
    host=${host%%.*}

    width=$(tput cols)

    ls -pt -G | xargs > /tmp/blah    
    lines=$(wc -l < /tmp/blah )
    echo $lines
    tput -S <<< "
        cup $(( $lines + 2 )) 0
        el
        cup 0 0
    "
    if [ $(whoami) == "root" ]; then
        symb="■"
    else 
        symb="●"
    fi

    cat /tmp/blah | gawk ' 
    BEGIN {
        "tput cols" | getline width
        "date" | getline date
        printf "┏"
        w = width
        dateLength = length(date);
        while (--w > dateLength + 2) {
            printf "━";
        }
        printf date
        printf "━┓\n"
    } 
    {
        w = width - 4;
        printf "┃ %-"w"s ┃\n", substr($0, 0, length($0))
    }
    END {
        printf "┗"
        w = width
        while (--w > 1) {
            printf "━";
        }
        printf "┛\n"
    }
    '

    echo "$host..$(basename $(pwd))/$symb "
}

function 9man {
    if [[ $# -eq 0 ]]; then
        man
        return 
    fi
    cat $(/usr/bin/env man $@ -w) | 9 troff -N -mantimes | 9 sed '
            ${
                    /^$/p
            }
            //N
            /^\n$/D
    ' | less
}
