#! /usr/bin/env bash

function mancat {
    man -P cat $@ | col -b 
}

#function cd {
#   command cd $1; 
#   ls;
#}

function ju {
    first=$1
    shift;
    cd $(find $first -type d | fzf --query="$@")
}

function get_ps1 {
    tput -S <<< "
        cup 0 0
        el
        cup 1 0
        el
        cup 0 0
    "
    host=$(hostname)
    host=${host%%.*}

    ls -pt -G | xargs >/tmp/_    
    lines=$(wc -l /tmp/_)
    tput -S <<< "
        cup $lines 0
        el
        cup 0 0
    "
    if [ $(whoami) = "root" ]; then
        symb="■"
    else 
        symb="●"
    fi

    cat /tmp/_
    echo "$host..$(basename $(pwd))/$symb "
}
