" Load pathogen plugins
execute pathogen#infect()
filetype plugin indent on

" Make switching buffers/tabs easy
nmap <Leader>b :ls<CR>:buffer!<Space>
nmap <Leader>t :tabs<CR>:tabn<Space>

imap \ <Esc>
vmap \ <Esc>
inoremap <C-\> \
nnoremap \ :noh<CR>
map <down> <C-d>zz
map <up> <C-u>zz
nnoremap <tab> zz
nnoremap '. '.zz
nnoremap j gj
nnoremap k gk

" Readline bindings for command mode
cnoremap <C-a> <Home>
cnoremap <C-e> <End>
cnoremap <C-p> <Up>
cnoremap <C-n> <Down>
cnoremap <C-b> <Left>
cnoremap <C-f> <Right>
cnoremap <C-d> <Del>
cnoremap <C-h> <BS>
cnoremap <C-x><C-e> <C-f>
cnoremap <C-r> <C-f>?
cnoremap <C-s> <C-f>/
" The bindings below ought to be <M-...>, this is specific to 0SX
cnoremap <C-[>b <S-Left>
cnoremap <C-[>f <S-Right>
nnoremap <space> :w<CR>
nnoremap Q :bd<CR>
noremap ;; :%s:::g<Left><Left><Left>
"Javascript convenience
inoremap <C-l> console.log("")<Left><Left>
"Yank the current buffer full path to clipboard
nnoremap <silent> -y :let @+ = expand("%:p")<CR>
nnoremap <silent> -[ <C-O>
nnoremap <silent> -] <C-I>
" v(imrc)
noremap <silent> -v :tabe ~/.vimrc<CR>
" s(hell)
noremap <silent> -s :shell<CR>
" t(rim) whitespace

" Use Vim settings, rather than Vi settings (much better!).
set nocompatible
set foldmethod=syntax
set expandtab
set softtabstop=4
set shiftwidth=4
set pastetoggle=<F2>
set noswapfile
set showmode
set history=50		" keep 50 lines of command line history
set ruler		" show the cursor position all the time
set showcmd		" display incomplete commands
set incsearch		" do incremental searching
set hlsearch
set autochdir
set noswapfile
set undofile
set nomore              " removes the annoying vim page message thing
set display=lastline    " display lines that extend past bottom
syntax on
set wildmode=longest:full
set wildmenu
set autoread
" Centralize backups, swapfiles and undo history
set backupdir=~/.vim/backups
set directory=~/.vim/swaps
if exists("&undodir")
    set undodir=~/.vim/undo
endif

colorscheme uncolor

highlight MatchParen cterm=underline " causes unmatched parens to be visible

" Disable auto commenting
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

" Let commentary default to #, if filetype is empty useful when opening cmd line and editing a bash/awk script
autocmd BufRead,BufNewFile * if &ft == '' | set commentstring=#\ %s | endif

autocmd BufDelete * if len(filter(range(1, bufnr('$')), '!empty(bufname(v:val)) && buflisted(v:val)')) == 1 | quit | endif
