# Source config
function _ {
    for file in \
        ~/.bashrc.local \
        ~/dotfiles/aliases \
        ~/dotfiles/functions \
        ~/dotfiles/scripts/z.sh \
        ~/dotfiles/complete/*; do
        [ -f $file ] && source $file
    done

    # If tty is connected to stdin
    if [ -t 0 ]; then
        # Enable C-s with readline
        stty -ixon -ixoff
    fi

    # Use common sense bindings for less
    export LESSKEY=~/dotfiles/less/lesskey.generated

    # History
    # If set, the history list is appended to the file on shell exit
    shopt -s histappend
    export HISTSIZE=
    export HISTFILESIZE=

    export TERM=xterm-256color
    export EDITOR="vim"

    # If we were in a virtualenv, reactivate it
    if [ -n "$VIRTUAL_ENV" ]; then
        DIR="$VIRTUAL_ENV";
        deactivate;
        if [ -e "$DIR/bin/activate" ]; then
            . "$DIR/bin/activate";
        fi;
    fi;
}

_;
