# Activate Connor's config
function _() {
    for file in \
        ~/.bashrc \
        ~/.bashrc.local \
        ~/dotfiles/aliases \
        ~/dotfiles/functions \
        ~/dotfiles/complete/*; do
        [ -f $file ] && source $file
    done

    # For Terminal to enable C-s with readline
    stty -ixon -ixoff

    # History
    # On interactive startup, Bash truncates $HISTFILE to $HISTFILESIZE
    # On interactive close, if the shell option histappend is set, Bash 
    #   appends $HISTSIZE lines to $HISTFILE, otherwise it overwrites $HISTFILE
    shopt -s histappend
    export HISTFILESIZE=
    export HISTSIZE=

    # export PROMPT_COMMAND="history -a ~/.bash_history.global"
    # \\export PS1='[\h:\W]> ' 
    export PS1='\h:\W \u\$ ' 
    export TERM=xterm-256color
    export EDITOR="vim"

    # If we were in a virtualenv, reactivate it
    if [ -n "$VIRTUAL_ENV" ]; then
        DIR="$VIRTUAL_ENV";
        deactivate;
        if [ -e "$DIR/bin/activate" ]; then
            . "$DIR/bin/activate";
        fi;
    fi;
}
