# Source

for file in \
    ~/.bashrc.local \
    ~/dotfiles/aliases \
    ~/dotfiles/functions \
    ~/dotfiles/complete/*; do
    [ -f $file ] && source $file
done

# Readline

# For Terminal to enable C-s with readline
stty -ixon -ixoff

# History

# On interactive startup, Bash truncates $HISTFILE to $HISTFILESIZE
# On interactive close, if the shell option histappend is set, Bash 
#   appends $HISTSIZE lines to $HISTFILE, otherwise it overwrites $HISTFILE
shopt -s histappend

# Prompt 
# export PROMPT_COMMAND="history -a ~/.bash_history.global"
PS1='[\h:\W]> ' 

# Exports

export TERM=xterm-256color
export EDITOR="vim"
export PATH=~/dotfiles/awk:/usr/local/opt/coreutils/libexec/gnubin:$PATH
export AWKPATH=~/dotfiles/awk
export HISTFILESIZE=
export HISTSIZE=

if [[ `hostname` == "toad" ]]; then
    # Source local awk (less compliant) scripts first
    export AWKPATH=~/proj/awk:$AWKPATH
    export PATH=~/proj/awk:$PATH
fi

# List open screen sessions
shopt -q login_shell && screen -ls
