#!/bin/bash

if [ $# -lt  2 ]
then
    echo "git common-ancestor <commit> <commit>";
    exit 1;
fi

COMMON_ANCESTOR=""
while read sha1 <&3  && read sha2 <&4
do
    if [ "$sha1" == "$sha2" ];
    then
        COMMON_ANCESTOR="$sha1";
    else
        if [ -n "$COMMON_ANCESTOR" ];
        then
            echo $COMMON_ANCESTOR;
        fi;
        break;
    fi;

done 3< <(git log --reverse --pretty=format:'%H' "$1") 4< <(git log --reverse --pretty=format:'%H' "$2")
